version: "3"
services:
  users_service:
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@users_service_db:5432/users_test?sslmode=disable

  famous_news_service:
    environment:
      - QUERYBD_HOST=mongodb://querydb_famous:27017/news_test
      - COMMANDDB_HOST=postgresql://postgres:postgres@commanddb_famous:5432/news_test?sslmode=disable

  politics_news_service:
    environment:
      - QUERYBD_HOST=mongodb://querydb_politics:27017/news_test
      - COMMANDDB_HOST=postgresql://postgres:postgres@commanddb_politics:5432/news_test?sslmode=disable

  sports_news_service:
    environment:
      - QUERYBD_HOST=mongodb://querydb_sports:27017/news_test
      - COMMANDDB_HOST=postgresql://postgres:postgres@commanddb_sports:5432/news_test?sslmode=disable

  recommendation_service:
    environment:
      - DATABASE_URL=http://recommendation_db:7474/db/test_data
